/**
 * Die deutschen Zeilen.
 */

import type { PartialTexts } from './en'

export const DE: PartialTexts = {
  description: 'Bereich der Modelle und Effort-Stufen, mit einem Klick gewechselt (/dash opus, /dash high, /dash quick)',
  argumentHint: '[Modell|Effort|Vorgabe|set]',
  settingsTitle: 'Einstellungen — /dash set <Schlüssel> <Wert>, ohne Wert für den Standard:',
  settingUnknown: 'Unbekannte Einstellung; eine von:',
  settingBadLanguage: 'Unbekannte Sprache; eine von:',
  settingSaved: 'Einstellung gespeichert:',
  paneTitle: 'Dash',
  opened: 'Bereich Dash geöffnet.',
  models: 'Modell',
  efforts: 'Effort',
  presets: 'Vorgaben',
  unknown: 'unbekannt',
  noEffort: 'Dieses Modell kennt keine Effort-Einstellung.',
  noEffortShort: 'ohne Effort',
  heldEffort: 'vom Mod bei jeder Anfrage gesetzt (hier gibt es kein /effort)',
  asked: 'angefordert',
  unknownPick: 'Weder ein Modell noch ein Effort noch eine Vorgabe:',
  modelSet: 'Modell angefordert:',
  effortSet: 'Effort angefordert:',
  presetSet: 'Vorgabe angefordert:',
  failed: 'Der Wechsel hat nicht gegriffen:',
  notReady: 'Die Sitzung ist noch nicht bereit: gleich noch einmal versuchen.',
  already: 'bereits auf',
  preset: 'Vorgabe',
  fast: 'Schnellmodus',
  ultracodeOn: 'an',
  ultracodeOff: 'aus',
  ultracodeSet: 'Ultracode angefordert:',
  moreModels: 'Weitere',
  workflowSize: 'Workflows:',
  maxAgents: 'Max. Agenten',
  maxAgentsNone: 'keine Grenze',
  capNamed: cap =>
    `dash: Eine Agenten-Obergrenze (${cap}) ist gesetzt, und ein per Name gestarteter Workflow lässt sich nicht begrenzen. Übergeben Sie das Skript direkt.`,
  capUnfit: cap =>
    `dash: Eine Agenten-Obergrenze (${cap}) ist gesetzt, und dieses Skript hat kein Literal export const meta = {...}, hinter das sie passt.`,
  settingBadMaxAgents: 'Keine Obergrenze: eine ganze Zahl von Agenten, ab 1.',
  agents: 'Subagenten',
  agentsMore: hidden => `Aufklappen (+${hidden})`,
  agentsLess: 'Zuklappen',
  commands: 'Befehle',
  skills: 'Skills',
  libraryNone: 'Keine.',
  libraryHint: 'ein Klick setzt es an den Anfang der Eingabe; nichts wird gesendet',
  commandPut: command => `${command} in die Eingabe gesetzt: senden Sie es, um es auszuführen.`,
  keyboard: 'Tastenkürzel:',
  keyboardOn: 'sichtbar',
  keyboardOff: 'ausgeblendet',
  settingBadKeyboard: 'Tastatur: on oder off.',
  compactMode: 'Kompaktmodus:',
  settingBadCompact: 'Kompaktmodus: on oder off.',
  settingBadBand: 'Leiste: model, effort, session, durch Kommas getrennt.',
  bandPut: 'in der Leiste über dem Prompt',
  bandTaken: 'aus der Leiste über dem Prompt entfernt',
  session: 'Sitzung',
  context: 'Ktx:',
  renameLabel: 'Name',
  renamePlaceholder: 'Sitzung umbenennen',
  renameSubmit: 'umbenennen',
  renamed: name => `Sitzung umbenannt: ${name}`,
  compactAsk: 'Kontext kompaktieren?',
  compactYes: 'ja',
  compactNoteLabel: 'Anweisungen',
  compactNoteHint: 'optional',
  compactSubmit: 'kompaktieren',
  compactNo: 'nein',
  library: 'Bibliothek',
  config: 'Einstellungen',
  configHint: 'jede Zeile ändert die /config-Einstellung sofort',
  configRefused: 'Einstellung abgelehnt:',
  newPreset: 'Neue Voreinstellung',
  presetName: 'Name',
  presetNameHint: 'Kleinbuchstaben, Ziffern, Bindestriche',
  presetModel: 'Modell',
  presetEffort: 'Aufwand',
  presetEffortDefault: 'die des Modells',
  presetAdd: 'Hinzufügen',
  presetAdded: 'Voreinstellung hinzugefügt:',
  presetExists: 'Eine Voreinstellung trägt diesen Namen schon.',
  presetBadName:
    'Kein gültiger Name: Kleinbuchstaben, Ziffern und Bindestriche, mit einem Buchstaben am Anfang, und kein Modell- oder Stufenname.',
  presetDeleted: 'Voreinstellung gelöscht:',
  plugins: 'Plugins',
  mcp: 'MCP-Server',
  hooks: 'Hooks',
  toggleHint: 'ein Klick schaltet es ein oder aus (● an, ○ aus)',
  hooksHint: 'die Hooks der Einstellungen, nach Ereignis; /hooks zum Ändern',
  pluginToggled: (name, isOn) => `${name} ${isOn ? 'aktiviert' : 'deaktiviert'}: ↻ /reload-plugins im Bereich wendet es an.`,
  serverToggled: (name, isOn) => `MCP ${name} ${isOn ? 'aktiviert' : 'deaktiviert'}.`,
  scopeUser: 'Global',
  scopeProject: 'Projekt',
  agentPut: mention => `${mention} in die Eingabe gesetzt: Ihre nächste Nachricht geht an ihn.`,
  agentNotPut: 'Die Eingabe ist belegt (ein Dialog ist offen): nichts gesetzt.',
  ignored: 'In den Einstellungen ignoriert:',
  costNone: 'Noch keine Anfrage: Wechseln kostet nichts.',
  costCold: 'Cache abgelaufen: Wechseln kostet nichts mehr.',
  costMethod: 'Tokens gemessen an der letzten Anfrage',
  costWarm: tokens => `⚠ Warmer Cache: Wechseln schreibt ${tokens} Tokens zum vollen Preis neu.`,
  costMaybe: tokens =>
    `Cache vielleicht abgelaufen (TTL 5 min oder 1 h): Wechseln kostet höchstens ${tokens} Tokens zum vollen Preis.`,
  costSuffix: tokens => ` · ${tokens} Tokens neu zu cachen`,
  spent: 'Kosten:',
  usd: usd => `${usd.toFixed(2).replace('.', ',')} $`,
  elapsed: 'Dauer:',
  limitFiveHour: '5 h:',
  limitSevenDay: 'Woche:',
  limitSpend: 'Ausgabenlimit:',
  dayUnit: 'T',
  taglines: { fable: 'das stärkste', opus: 'gründlich', sonnet: 'ausgewogen', haiku: 'schnell' },
}
