/**
 * The English lines: the complete bundle, the shape every other language
 * follows, and the fallback for any line a translation leaves out.
 */

export const EN = {
  description: 'Pane of the models and the effort levels, switched in one click (/dash opus, /dash high, /dash quick)',
  argumentHint: '[model|effort|preset|set]',
  settingsTitle: 'Settings — /dash set <key> <value>, no value for the default:',
  settingUnknown: 'No such setting; one of:',
  settingBadLanguage: 'No such language; one of:',
  settingSaved: 'Setting saved:',
  paneTitle: 'Dash',
  opened: 'Dash pane opened.',
  models: 'Model',
  efforts: 'Effort',
  presets: 'Presets',
  unknown: 'unknown',
  noEffort: 'This model takes no effort setting.',
  noEffortShort: 'no effort',
  heldEffort: 'applied by the mod on each request (no /effort here)',
  asked: 'asked',
  unknownPick: 'Neither a model, an effort nor a preset:',
  modelSet: 'Model asked:',
  effortSet: 'Effort asked:',
  presetSet: 'Preset asked:',
  failed: 'The switch did not take:',
  notReady: 'The session is not ready yet: try again in a moment.',
  already: 'already on',
  preset: 'Preset',
  fast: 'Fast mode',
  ultracode: 'Ultracode',
  ultracodeOn: 'on',
  ultracodeOff: 'off',
  ultracodeSet: 'Ultracode asked:',
  moreModels: 'Other',
  workflowSize: 'Workflows:',
  maxAgents: 'Max agents',
  maxAgentsNone: 'no cap',
  capNamed: (cap: string): string =>
    `dash: an agent cap (${cap}) is set and a workflow run by name cannot be capped. Pass the script inline instead.`,
  capUnfit: (cap: string): string =>
    `dash: an agent cap (${cap}) is set and this script has no export const meta = {...} literal to put it after.`,
  settingBadMaxAgents: 'Not a cap: a whole number of agents, 1 or more.',
  agents: 'Subagents',
  agentsMore: (hidden: number): string => `Expand (+${hidden})`,
  agentsLess: 'Collapse',
  commands: 'Commands',
  skills: 'Skills',
  libraryNone: 'None.',
  libraryHint: 'a click puts it at the head of the prompt; nothing is sent',
  commandPut: (command: string): string => `${command} put in the prompt: send it to run it.`,
  keyboard: 'Keyboard shortcuts:',
  keyboardOn: 'shown',
  keyboardOff: 'hidden',
  settingBadKeyboard: 'Keyboard: on or off.',
  compactMode: 'Compact mode:',
  settingBadCompact: 'Compact mode: on or off.',
  settingBadBand: 'Band: model, effort, session, comma-separated.',
  bandPut: 'in the band above the prompt',
  bandTaken: 'out of the band above the prompt',
  session: 'Session',
  context: 'Ctx:',
  renameLabel: 'Name',
  renamePlaceholder: 'rename the session',
  renameSubmit: 'rename',
  renamed: (name: string): string => `Session renamed: ${name}`,
  compactAsk: 'Compact the context?',
  compactYes: 'yes',
  compactNoteLabel: 'Instructions',
  compactNoteHint: 'optional',
  compactSubmit: 'compact',
  compactNo: 'no',
  library: 'Library',
  config: 'Settings',
  configHint: 'each row changes the /config setting at once',
  configRefused: 'Setting refused:',
  newPreset: 'New preset',
  presetName: 'Name',
  presetNameHint: 'lowercase, digits, dashes',
  presetModel: 'Model',
  presetEffort: 'Effort',
  presetEffortDefault: "the model's own",
  presetAdd: 'Add',
  presetAdded: 'Preset added:',
  presetExists: 'A preset already has that name.',
  presetBadName:
    'Not a preset name: lowercase letters, digits and dashes, starting with a letter, and not the name of a model or a level.',
  presetDeleted: 'Preset deleted:',
  plugins: 'Plugins',
  mcp: 'MCP servers',
  hooks: 'Hooks',
  toggleHint: 'a click turns it on or off (● on, ○ off)',
  hooksHint: 'the settings hooks, by event; /hooks to change them',
  pluginToggled: (name: string, isOn: boolean): string =>
    `${name} ${isOn ? 'enabled' : 'disabled'}: ↻ /reload-plugins in the pane applies it.`,
  serverToggled: (name: string, isOn: boolean): string => `MCP ${name} ${isOn ? 'enabled' : 'disabled'}.`,
  scopeUser: 'Global',
  scopeProject: 'Project',
  agentPut: (mention: string): string => `${mention} put in the prompt: your next message goes to it.`,
  agentNotPut: 'The prompt box is busy (a dialog is open): nothing put.',
  ignored: 'Ignored in the settings:',
  costNone: 'No request yet: switching costs nothing.',
  costCold: 'Cache expired: switching costs nothing more.',
  costMethod: 'tokens measured on the last request',
  costWarm: (tokens: string): string => `⚠ Warm cache: switching rewrites ${tokens} tokens at full price.`,
  costMaybe: (tokens: string): string =>
    `Cache maybe expired (TTL 5 min or 1 h): switching costs at most ${tokens} tokens at full price.`,
  costSuffix: (tokens: string): string => ` · ${tokens} tokens to cache again`,
  spent: 'Cost:',
  usd: (usd: number): string => `$${usd.toFixed(2)}`,
  elapsed: 'Duration:',
  limitFiveHour: '5 h:',
  limitSevenDay: 'Week:',
  limitSpend: 'Spend limit:',
  limitResets: (when: string): string => `resets in ${when}`,
  dayUnit: 'd',
  taglines: {
    fable: 'strongest',
    opus: 'deep',
    sonnet: 'balanced',
    haiku: 'fast',
  } as Record<string, string>,
}

/**
 * Every line of the mod.
 */
export type Texts = typeof EN

/**
 * A translation: the lines it has, the others drawn in English.
 */
export type PartialTexts = Partial<Texts>
