/**
 * Las líneas en español.
 */

import type { PartialTexts } from './en'

export const ES: PartialTexts = {
  description: 'Panel de modelos y niveles de esfuerzo, cambiados con un clic (/dash opus, /dash high, /dash quick)',
  argumentHint: '[modelo|esfuerzo|preajuste|set]',
  settingsTitle: 'Ajustes — /dash set <clave> <valor>, sin valor para el predeterminado:',
  settingUnknown: 'Ajuste desconocido; uno de:',
  settingBadLanguage: 'Idioma desconocido; uno de:',
  settingSaved: 'Ajuste guardado:',
  paneTitle: 'Dash',
  opened: 'Panel Dash abierto.',
  models: 'Modelo',
  efforts: 'Esfuerzo',
  presets: 'Preajustes',
  unknown: 'desconocido',
  noEffort: 'Este modelo no admite ajuste de esfuerzo.',
  noEffortShort: 'sin esfuerzo',
  heldEffort: 'aplicado por el mod en cada petición (aquí no hay /effort)',
  asked: 'pedido',
  unknownPick: 'Ni un modelo, ni un esfuerzo, ni un preajuste:',
  modelSet: 'Modelo pedido:',
  effortSet: 'Esfuerzo pedido:',
  presetSet: 'Preajuste pedido:',
  failed: 'El cambio no se aplicó:',
  notReady: 'La sesión aún no está lista: inténtelo de nuevo en un momento.',
  already: 'ya en',
  preset: 'Preajuste',
  fast: 'Modo rápido',
  ultracodeOn: 'activado',
  ultracodeOff: 'desactivado',
  ultracodeSet: 'Ultracode pedido:',
  moreModels: 'Otros',
  workflowSize: 'Workflows:',
  maxAgents: 'Agentes máx.',
  maxAgentsNone: 'sin tope',
  capNamed: cap =>
    `dash: hay un tope de agentes (${cap}) y un workflow lanzado por su nombre no se puede limitar. Pase el script en línea.`,
  capUnfit: cap =>
    `dash: hay un tope de agentes (${cap}) y este script no tiene un literal export const meta = {...} tras el que ponerlo.`,
  settingBadMaxAgents: 'No es un tope: un número entero de agentes, 1 o más.',
  agents: 'Subagentes',
  agentsMore: hidden => `Desplegar (+${hidden})`,
  agentsLess: 'Plegar',
  commands: 'Comandos',
  skills: 'Skills',
  libraryNone: 'Ninguno.',
  libraryHint: 'un clic lo pone al inicio del campo; no se envía nada',
  commandPut: command => `${command} puesto en el campo: envíelo para ejecutarlo.`,
  keyboard: 'Atajos de teclado:',
  keyboardOn: 'visibles',
  keyboardOff: 'ocultos',
  settingBadKeyboard: 'Teclado: on u off.',
  compactMode: 'Modo compacto:',
  settingBadCompact: 'Modo compacto: on u off.',
  settingBadBand: 'Banda: model, effort, session, separados por comas.',
  bandPut: 'en la banda sobre el prompt',
  bandTaken: 'fuera de la banda sobre el prompt',
  session: 'Sesión',
  context: 'Ctx:',
  renameLabel: 'Nombre',
  renamePlaceholder: 'renombrar la sesión',
  renameSubmit: 'renombrar',
  renamed: name => `Sesión renombrada: ${name}`,
  compactAsk: '¿Compactar el contexto?',
  compactYes: 'sí',
  compactNoteLabel: 'Instrucciones',
  compactNoteHint: 'opcional',
  compactSubmit: 'compactar',
  compactNo: 'no',
  library: 'Biblioteca',
  config: 'Ajustes',
  configHint: 'cada fila cambia el ajuste de /config al instante',
  configRefused: 'Ajuste rechazado:',
  newPreset: 'Nuevo preajuste',
  presetName: 'Nombre',
  presetNameHint: 'minúsculas, cifras, guiones',
  presetModel: 'Modelo',
  presetEffort: 'Esfuerzo',
  presetEffortDefault: 'el del modelo',
  presetAdd: 'Añadir',
  presetAdded: 'Preajuste añadido:',
  presetExists: 'Ya hay un preajuste con ese nombre.',
  presetBadName:
    'Nombre no válido: minúsculas, cifras y guiones, empezando por una letra, y no el nombre de un modelo o de un nivel.',
  presetDeleted: 'Preajuste eliminado:',
  plugins: 'Plugins',
  mcp: 'Servidores MCP',
  hooks: 'Hooks',
  toggleHint: 'un clic lo activa o lo desactiva (● activo, ○ inactivo)',
  hooksHint: 'los hooks de los ajustes, por evento; /hooks para cambiarlos',
  pluginToggled: (name, isOn) => `${name} ${isOn ? 'activado' : 'desactivado'}: ↻ /reload-plugins en el panel lo aplica.`,
  serverToggled: (name, isOn) => `MCP ${name} ${isOn ? 'activado' : 'desactivado'}.`,
  scopeUser: 'Global',
  scopeProject: 'Proyecto',
  agentPut: mention => `${mention} puesto en el campo: su próximo mensaje va a él.`,
  agentNotPut: 'El campo está ocupado (hay un diálogo abierto): no se puso nada.',
  ignored: 'Ignorado en los ajustes:',
  costNone: 'Aún no hay petición: cambiar no cuesta nada.',
  costCold: 'Caché caducada: cambiar no cuesta nada más.',
  costMethod: 'tokens medidos en la última petición',
  costWarm: tokens => `⚠ Caché caliente: cambiar reescribe ${tokens} tokens a precio completo.`,
  costMaybe: tokens =>
    `Caché quizá caducada (TTL 5 min o 1 h): cambiar cuesta como mucho ${tokens} tokens a precio completo.`,
  costSuffix: tokens => ` · ${tokens} tokens que volver a cachear`,
  spent: 'Coste:',
  usd: usd => `${usd.toFixed(2).replace('.', ',')} US$`,
  elapsed: 'Duración:',
  limitFiveHour: '5 h:',
  limitSevenDay: 'Semana:',
  limitSpend: 'Límite de gasto:',
  limitResets: when => `se reinicia en ${when}`,
  dayUnit: 'd',
  taglines: { fable: 'el más potente', opus: 'profundo', sonnet: 'equilibrado', haiku: 'rápido' },
}
