/**
 * Les lignes en français.
 */

import type { PartialTexts } from './en'

export const FR: PartialTexts = {
  description: 'Panneau des modèles et des efforts, à changer d’un clic (/dash opus, /dash high, /dash quick)',
  argumentHint: '[modèle|effort|préréglage|set]',
  settingsTitle: 'Réglages — /dash set <clé> <valeur>, sans valeur pour le défaut :',
  settingUnknown: 'Réglage inconnu ; au choix :',
  settingBadLanguage: 'Langue inconnue ; au choix :',
  settingSaved: 'Réglage enregistré :',
  paneTitle: 'Dash',
  opened: 'Panneau Dash ouvert.',
  models: 'Modèle',
  efforts: 'Effort',
  presets: 'Préréglages',
  unknown: 'inconnu',
  noEffort: 'Ce modèle ne prend pas de réglage d’effort.',
  noEffortShort: 'sans effort',
  heldEffort: 'appliqué par le mod à chaque requête (pas de /effort ici)',
  asked: 'demandé',
  unknownPick: 'Ni un modèle, ni un effort, ni un préréglage :',
  modelSet: 'Modèle demandé :',
  effortSet: 'Effort demandé :',
  presetSet: 'Préréglage demandé :',
  failed: 'Le changement n’a pas pris :',
  notReady: 'La session n’est pas encore prête : réessayez dans un instant.',
  already: 'déjà sur',
  preset: 'Préréglage',
  fast: 'Mode rapide',
  ultracodeOn: 'activé',
  ultracodeOff: 'désactivé',
  ultracodeSet: 'Ultracode demandé :',
  moreModels: 'Autres',
  workflowSize: 'Workflows :',
  maxAgents: 'Agents max',
  maxAgentsNone: 'sans plafond',
  capNamed: cap =>
    `dash : un plafond d’agents (${cap}) est réglé et un workflow lancé par son nom ne peut pas être plafonné. Passez le script en ligne.`,
  capUnfit: cap =>
    `dash : un plafond d’agents (${cap}) est réglé et ce script n’a pas de littéral export const meta = {...} après lequel le poser.`,
  settingBadMaxAgents: 'Pas un plafond : un nombre entier d’agents, 1 ou plus.',
  agents: 'Sous-agents',
  agentsMore: hidden => `Développer (+${hidden})`,
  agentsLess: 'Réduire',
  commands: 'Commandes',
  skills: 'Skills',
  libraryNone: 'Aucun.',
  libraryHint: 'un clic le met en tête du champ de saisie ; rien n’est envoyé',
  commandPut: command => `${command} mis dans le champ de saisie : envoyez-le pour l’exécuter.`,
  keyboard: 'Raccourcis clavier :',
  keyboardOn: 'affichés',
  keyboardOff: 'masqués',
  settingBadKeyboard: 'Clavier : on ou off.',
  compactMode: 'Mode compact :',
  settingBadCompact: 'Mode compact : on ou off.',
  settingBadBand: 'Bande : model, effort, session, séparés par des virgules.',
  bandPut: 'dans la bande au-dessus du prompt',
  bandTaken: 'retiré de la bande au-dessus du prompt',
  session: 'Session',
  context: 'Ctx :',
  renameLabel: 'Nom',
  renamePlaceholder: 'renommer la session',
  renameSubmit: 'renommer',
  renamed: name => `Session renommée : ${name}`,
  compactAsk: 'Compacter le contexte ?',
  compactYes: 'oui',
  compactNoteLabel: 'Instructions',
  compactNoteHint: 'facultatif',
  compactSubmit: 'compacter',
  compactNo: 'non',
  library: 'Bibliothèque',
  config: 'Réglages',
  configHint: 'chaque ligne change le réglage de /config aussitôt',
  configRefused: 'Réglage refusé :',
  newPreset: 'Nouveau préréglage',
  presetName: 'Nom',
  presetNameHint: 'minuscules, chiffres, tirets',
  presetModel: 'Modèle',
  presetEffort: 'Effort',
  presetEffortDefault: 'celui du modèle',
  presetAdd: 'Ajouter',
  presetAdded: 'Préréglage ajouté :',
  presetExists: 'Un préréglage porte déjà ce nom.',
  presetBadName:
    'Nom invalide : minuscules, chiffres et tirets, commençant par une lettre, et pas le nom d’un modèle ou d’un niveau.',
  presetDeleted: 'Préréglage supprimé :',
  plugins: 'Plugins',
  mcp: 'Serveurs MCP',
  hooks: 'Hooks',
  toggleHint: 'un clic l’active ou le désactive (● actif, ○ inactif)',
  hooksHint: 'les hooks des réglages, par événement ; /hooks pour les modifier',
  pluginToggled: (name, isOn) => `${name} ${isOn ? 'activé' : 'désactivé'} : ↻ /reload-plugins dans le panneau l’applique.`,
  serverToggled: (name, isOn) => `MCP ${name} ${isOn ? 'activé' : 'désactivé'}.`,
  scopeUser: 'Global',
  scopeProject: 'Projet',
  agentPut: mention => `${mention} mis dans le champ de saisie : votre prochain message lui est confié.`,
  agentNotPut: 'Le champ de saisie est occupé (une boîte de dialogue est ouverte) : rien n’a été mis.',
  ignored: 'Ignoré dans les réglages :',
  costNone: 'Pas encore de requête : changer ne coûte rien.',
  costCold: 'Cache expiré : changer ne coûte rien de plus.',
  costMethod: 'tokens mesurés sur la dernière requête',
  costWarm: tokens => `⚠ Cache chaud : changer fait réécrire ${tokens} tokens au prix plein.`,
  costMaybe: tokens =>
    `Cache peut-être expiré (TTL 5 min ou 1 h) : changer coûte au plus ${tokens} tokens au prix plein.`,
  costSuffix: tokens => ` · ${tokens} tokens à remettre en cache`,
  spent: 'Coût :',
  usd: usd => `${usd.toFixed(2).replace('.', ',')} $`,
  elapsed: 'Durée :',
  limitFiveHour: '5 h :',
  limitSevenDay: 'Semaine :',
  limitSpend: 'Plafond de dépense :',
  limitResets: when => `réinitialisé dans ${when}`,
  dayUnit: 'j',
  taglines: { fable: 'le plus fort', opus: 'profond', sonnet: 'équilibré', haiku: 'rapide' },
}
